# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        user_image:
            uri_prefix: /img/users
            upload_destination: '%kernel.project_dir%/public/img/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

